const highballGlass = 'Highball glass';
const cockTailGlass = 'Cocktail glass';
const ordinaryDrink = 'Ordinary drink';
const orangeJuice = 'Orange juice';

export const drinkIngredientLemon = {
  drinks: [
    {
      strDrink: 'A True Amaretto Sour',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rptuxy1472669372.jpg',
      idDrink: '17005',
    },
    {
      strDrink: 'Boston Sour',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/kxlgbi1504366100.jpg',
      idDrink: '11129',
    },
    {
      strDrink: 'Brandy Cobbler',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/5xgu591582580586.jpg',
      idDrink: '11157',
    },
    {
      strDrink: 'Brandy Sour',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/b1bxgq1582484872.jpg',
      idDrink: '11170',
    },
    {
      strDrink: 'California Lemonade',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/q5z4841582484168.jpg',
      idDrink: '11205',
    },
    {
      strDrink: 'Chicago Fizz',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/qwvwqr1441207763.jpg',
      idDrink: '11242',
    },
    {
      strDrink: 'Clover Club',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/t0aja61504348715.jpg',
      idDrink: '17186',
    },
    {
      strDrink: 'Frisco Sour',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/acuvjz1582482022.jpg',
      idDrink: '11382',
    },
    {
      strDrink: 'Gin Fizz',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/drtihp1606768397.jpg',
      idDrink: '11410',
    },
    {
      strDrink: 'Gin Rickey',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/s00d6f1504883945.jpg',
      idDrink: '17230',
    },
    {
      strDrink: 'Gin Sling',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/8cl9sm1582581761.jpg',
      idDrink: '11415',
    },
    {
      strDrink: 'Grape lemon pineapple Smoothie',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/54z5h71487603583.jpg',
      idDrink: '12712',
    },
    {
      strDrink: 'Imperial Fizz',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/zj1usl1504884548.jpg',
      idDrink: '11524',
    },
    {
      strDrink: 'Japanese Fizz',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/37vzv11504884831.jpg',
      idDrink: '11558',
    },
    {
      strDrink: 'Kill the cold Smoothie',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/7j1z2e1487603414.jpg',
      idDrink: '12720',
    },
    {
      strDrink: 'Lemon Drop',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/mtpxgk1504373297.jpg',
      idDrink: '14366',
    },
    {
      strDrink: 'Lemon Shot',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/mx31hv1487602979.jpg',
      idDrink: '12752',
    },
    {
      strDrink: 'Lemouroudji',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/eirmo71487603745.jpg',
      idDrink: '12702',
    },
    {
      strDrink: 'New York Sour',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/61wgch1504882795.jpg',
      idDrink: '11844',
    },
    {
      strDrink: 'Quaker\'s Cocktail',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/yrqppx1478962314.jpg',
      idDrink: '11983',
    },
    {
      strDrink: 'Royal Gin Fizz',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/pe1x1c1504735672.jpg',
      idDrink: '12057',
    },
    {
      strDrink: 'Rum Cobbler',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/5vh9ld1504390683.jpg',
      idDrink: '12067',
    },
    {
      strDrink: 'Rum Cooler',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/2hgwsb1504888674.jpg',
      idDrink: '12071',
    },
    {
      strDrink: 'Sangria The  Best',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vysywu1468924264.jpg',
      idDrink: '13026',
    },
    {
      strDrink: 'Sidecar Cocktail',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/ewjxui1504820428.jpg',
      idDrink: '12198',
    },
    {
      strDrink: 'Snowball',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/7ibfs61504735416.jpg',
      idDrink: '14195',
    },
    {
      strDrink: 'Strawberry Lemonade',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/spvvxp1468924425.jpg',
      idDrink: '13036',
    },
    {
      strDrink: 'Tequila Sour',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/ek0mlq1504820601.jpg',
      idDrink: '12370',
    },
    {
      strDrink: 'Vesuvio',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/26cq601492976203.jpg',
      idDrink: '12444',
    },
    {
      strDrink: 'Whiskey Sour',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/hbkfsh1589574990.jpg',
      idDrink: '11004',
    },
    {
      strDrink: 'White Wine Sangria',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/hnuod91587851576.jpg',
      idDrink: '178326',
    },
    {
      strDrink: 'Wine Punch',
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/txustu1473344310.jpg',
      idDrink: '13058',
    },
  ],
};

export const drinkNameCubaLibre = {
  drinks: [
    {
      idDrink: '11288',
      strDrink: 'Cuba Libre',
      strDrinkAlternate: null,
      strTags: 'IBA,ContemporaryClassic',
      strVideo: null,
      strCategory,
      strIBA: 'Contemporary Classics',
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Build all ingredients in a Collins glass filled with ice. Garnish with lime wedge.',
      strInstructionsES: null,
      strInstructionsDE: 'Geben Sie alle Zutaten in ein mit Eis gefülltes Collins-Glas. Mit Limettenkeil garnieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Mettere tutti gli ingredienti in un bicchiere Collins pieno di ghiaccio. Guarnire con uno spicchio di lime.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/wmkbfj1606853905.jpg',
      strIngredient1: 'Light rum',
      strIngredient2: 'Lime',
      strIngredient3: 'Coca-Cola',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: 'Juice of 1/2 ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://commons.wikimedia.org/wiki/File:Cuba_Libre.jpg',
      strImageAttribution: 'Martin Belam (currybet)',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-09-06 23:41:03',
    },
  ],
};

export const drinkFirstLetterA = {
  drinks: [
    {
      idDrink: '17222',
      strDrink: 'A1',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: cockTailGlass,
      strInstructions: 'Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.',
      strInstructionsES: 'Vierta todos los ingredientes en una coctelera, mezcle y sirva con hielo en un vaso frío.',
      strInstructionsDE: 'Alle Zutaten in einen Cocktailshaker geben, mischen und über Eis in ein gekühltes Glas servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare tutti gli ingredienti in uno shaker, mescolare e servire con ghiaccio in un bicchiere freddo.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Grand Marnier',
      strIngredient3: 'Lemon Juice',
      strIngredient4: 'Grenadine',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 3/4 shot ',
      strMeasure2: '1 Shot ',
      strMeasure3: '1/4 Shot',
      strMeasure4: '1/8 Shot',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-07 21:42:09',
    },
    {
      idDrink: '13501',
      strDrink: 'ABC',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Shot glass',
      strInstructions: 'Layered in a shot glass.',
      strInstructionsES: 'Coloque todos los ingredientes en un vaso de chupito.',
      strInstructionsDE: 'Schichtaufbau in einem Schnapsglas.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versa in ordine di lettera i vari ingredienti. 1/3 del bicchiere va riempito con l\'Amaretto, 1/3 di Baileys e il restante di Cognac.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg',
      strIngredient1: 'Amaretto',
      strIngredient2: 'Baileys irish cream',
      strIngredient3: 'Cognac',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/3 ',
      strMeasure2: '1/3 ',
      strMeasure3: '1/3 ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-08-31 19:32:08',
    },
    {
      idDrink: '17225',
      strDrink: 'Ace',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Martini Glass',
      strInstructions: 'Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.',
      strInstructionsES: 'Agite todos los ingredientes en una coctelera con hielo y entonces cuélelos sobre un vaso enfriado.',
      strInstructionsDE: 'Alle Zutaten in einem Cocktailshaker mit Eis schütteln und dann in einem kalten Glas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare tutti gli ingredienti in uno shaker e ghiaccio, quindi filtrare in un bicchiere freddo.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Grenadine',
      strIngredient3: 'Heavy cream',
      strIngredient4: 'Milk',
      strIngredient5: 'Egg White',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 shots ',
      strMeasure2: '1/2 shot ',
      strMeasure3: '1/2 shot ',
      strMeasure4: '1/2 shot',
      strMeasure5: '1/2 Fresh',
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-07 22:05:06',
    },
    {
      idDrink: '14610',
      strDrink: 'ACID',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Shot glass',
      strInstructions: 'Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.',
      strInstructionsES: 'Vierta primero el Bacardi 151, seguido del Wild Turkey 101 y sirva con Coca-Cola o Dr Pepper.',
      strInstructionsDE: 'Gering den 151 gefolgt von der 101, die mit einer Cola oder Dr. Pepper Chaser serviert wird.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versa prima il Bacardi 151 seguito dal 101, servito con una Coca-Cola.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg',
      strIngredient1: '151 proof rum',
      strIngredient2: 'Wild Turkey',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz Bacardi ',
      strMeasure2: '1 oz ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-11-15 11:28:37',
    },
    {
      idDrink: '17837',
      strDrink: 'Adam',
      strDrinkAlternate: null,
      strTags: 'Alcoholic,Holiday',
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: cockTailGlass,
      strInstructions: 'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.',
      strInstructionsES: 'Mezclar todos los ingredientes en una coctelera con cubitos de hielo hasta la mitad. Agitar bien. Colar el contenido en un vaso de cóctel.',
      strInstructionsDE: 'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT: 'In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg',
      strIngredient1: 'Dark rum',
      strIngredient2: 'Lemon juice',
      strIngredient3: 'Grenadine',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '1 tsp ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-09-02 11:29:29',
    },
    {
      idDrink: '13938',
      strDrink: 'AT&T',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Highball Glass',
      strInstructions: 'Pour Vodka and Gin over ice, add Tonic and Stir',
      strInstructionsES: 'Vierta el vodka y la ginebra sobre el hielo, agregue la tónica y revuelva.',
      strInstructionsDE: 'Wodka und Gin über das Eis gießen, Tonic hinzufügen und umrühren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare la vodka e il gin sul ghiaccio, aggiungere l\'acqua tonica e mescolare',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rhhwmp1493067619.jpg',
      strIngredient1: 'Absolut Vodka',
      strIngredient2: 'Gin',
      strIngredient3: 'Tonic water',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '4 oz ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-04-24 22:00:19',
    },
    {
      idDrink: '17833',
      strDrink: 'A. J.',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: cockTailGlass,
      strInstructions: 'Shake ingredients with ice, strain into a cocktail glass, and serve.',
      strInstructionsES: 'Agite bien los ingredientes con hielo, cuélelos en una copa de cóctel y sirva.',
      strInstructionsDE: null,
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/l74qo91582480316.jpg',
      strIngredient1: 'Applejack',
      strIngredient2: 'Grapefruit juice',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-09-02 11:16:58',
    },
    {
      idDrink: '17839',
      strDrink: 'Affair',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Pour schnapps, orange juice, and cranberry juice over ice in a highball glass. Top with club soda and serve.',
      strInstructionsES: 'Vierta el Schnapps, el jugo de naranja y el jugo de arándano sobre hielo en un vaso alto. Complete con el agua carbonatada y sirva.',
      strInstructionsDE: 'Gießen Sie Schnaps, Orangensaft und Cranberrysaft über Eis in ein Highball-Glas. Mit Club-Soda überziehen und servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare la grappa, il succo d\'arancia e il succo di mirtillo rosso sul ghiaccio in un bicchiere highball. Completare con la soda club e servire.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/h5za6y1582477994.jpg',
      strIngredient1: 'Strawberry schnapps',
      strIngredient2: orangeJuice,
      strIngredient3: 'Cranberry juice',
      strIngredient4: 'Club soda',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '2 oz ',
      strMeasure3: '2 oz ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-09-01 10:05:34',
    },
    {
      idDrink: '15106',
      strDrink: 'Apello',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Other/Unknown',
      strIBA: null,
      strAlcoholic: 'Non alcoholic',
      strGlass: 'Collins Glass',
      strInstructions: 'Stirr. Grnish with maraschino cherry.',
      strInstructionsES: 'Mezclar. Decorar con cereza marrasquino.',
      strInstructionsDE: 'Rühren. Mit Maraschinokirsche garnieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare tutti gli ingredienti in un mixing glass. Mescolate.\r\nGuarnire con una ciliegia al maraschino.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/uptxtv1468876415.jpg',
      strIngredient1: orangeJuice,
      strIngredient2: 'Grapefruit juice',
      strIngredient3: 'Apple juice',
      strIngredient4: 'Maraschino cherry',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '4 cl ',
      strMeasure2: '3 cl ',
      strMeasure3: '1 cl ',
      strMeasure4: '1 ',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-07-18 22:13:35',
    },
    {
      idDrink: '15266',
      strDrink: 'Avalon',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Fill a tall glass with ice. Layer the Finlandia Vodka, lemon and apple juices, Pisang Ambon, and top up with lemonade. Stir slightly and garnish with a spiralled cucumber skin and a red cherry. The cucumber provides zest and looks attractive. This drink, created by Timo Haimi, took first prize in the 1991 Finlandia Vodka Long Drink Competition.',
      strInstructionsES: 'Llena un vaso alto con hielo. Agregue el vodka, los jugos de limón y manzana, el licor de plátano Pisang Ambon y complete con limonada. Revuelva ligeramente y adorne con una cáscara de pepino en espiral y una cereza roja. El pepino proporciona entusiasmo y se ve atractivo. Esta bebida, creada por Timo Haimi, ganó el primer premio en el Concurso de Tragos Largos de Vodka de Finlandia de 1991.',
      strInstructionsDE: 'Füllen Sie ein hohes Glas mit Eis. Legen Sie den Finlandia Wodka, Zitronen- und Apfelsäfte, Pisang Ambon und geben Sie Limonade dazu. Leicht umrühren und mit einer spiralförmigen Gurkenhaut und einer roten Kirsche garnieren. Die Gurke sorgt für Schärfe und sieht attraktiv aus. Dieses von Timo Haimi kreierte Getränk erhielt 1991 den ersten Preis beim Finlandia Wodka Long Drink Wettbewerb.',
      strInstructionsFR: null,
      strInstructionsIT: 'Riempi un bicchiere alto di ghiaccio.\r\nVersare la Vodka, succhi di limone, mela, Pisang Ambon o un liquore alla banana e completare con la limonata.\r\nMescolare leggermente e guarnire con una buccia di cetriolo a spirale e una ciliegia rossa.\r\nIl cetriolo fornisce la scorza e sembra attraente.\r\nQuesta bevanda, creata da Timo Haimi, ha vinto il primo premio nel 1991 Finlandia Vodka Long Drink Competition.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/3k9qic1493068931.jpg',
      strIngredient1: 'Vodka',
      strIngredient2: 'Pisang Ambon',
      strIngredient3: 'Apple juice',
      strIngredient4: 'Lemon juice',
      strIngredient5: 'Lemonade',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '3 parts',
      strMeasure2: '1 part ',
      strMeasure3: '6 parts ',
      strMeasure4: '1 1/2 part ',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-04-24 22:22:11',
    },
    {
      idDrink: '17835',
      strDrink: 'Abilene',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Pour all of the ingredients into a highball glass almost filled with ice cubes. Stir well.',
      strInstructionsES: 'Coloque todos los ingredientes en un vaso alto casi lleno de cubitos de hielo. Sacudir bien.',
      strInstructionsDE: null,
      strInstructionsFR: null,
      strInstructionsIT: 'Versare tutti gli ingredienti in un bicchiere highball riempito di cubetti di ghiaccio. Mescolare bene.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/smb2oe1582479072.jpg',
      strIngredient1: 'Dark rum',
      strIngredient2: 'Peach nectar',
      strIngredient3: orangeJuice,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: '2 oz ',
      strMeasure3: '3 oz ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-04-29 09:44:25',
    },
    {
      idDrink: '17228',
      strDrink: 'Addison',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Martini Glass',
      strInstructions: 'Shake together all the ingredients and strain into a cold glass.',
      strInstructionsES: 'Agitar todos los ingredientes y colar la mezcla en un vaso enfriado.',
      strInstructionsDE: 'Alle Zutaten vermengen und in ein kaltes Glas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare insieme tutti gli ingredienti e filtrare in un bicchiere freddo.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/yzva7x1504820300.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Vermouth',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 shot ',
      strMeasure2: '1 1/2 shot ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-07 22:38:20',
    },
    {
      idDrink: '11023',
      strDrink: 'Almeria',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: cockTailGlass,
      strInstructions: 'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.',
      strInstructionsES: 'En una coctelera llena hasta la mitad con cubitos de hielo, mezcla todos los ingredientes. Agitar bien. Colar el contenido en un vaso de cóctel.',
      strInstructionsDE: 'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT: 'In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rwsyyu1483388181.jpg',
      strIngredient1: 'Dark rum',
      strIngredient2: 'Kahlua',
      strIngredient3: 'Egg white',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '1 ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-01-02 20:16:21',
    },
    {
      idDrink: '17836',
      strDrink: 'Acapulco',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Old-fashioned glass',
      strInstructions: 'Combine and shake all ingredients (except mint) with ice and strain into an old-fashioned glass over ice cubes. Add the sprig of mint and serve.',
      strInstructionsES: 'Mezcle y agite todos los ingredientes (excepto la menta) con hielo y cuélelos en un vaso de rocas sobre cubitos de hielo. Añadir una ramita de menta y servir.',
      strInstructionsDE: 'Alle Zutaten (außer Minze) mit Eis mischen und schütteln und in ein old-fashioned Glas über Eiswürfel abseihen. Den Minzzweig dazugeben und servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Unire e scuotere tutti gli ingredienti (tranne la menta) con ghiaccio e filtrare in un bicchiere vecchio stile su cubetti di ghiaccio.Aggiungere il rametto di menta e servire.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/il9e0r1582478841.jpg',
      strIngredient1: 'Light rum',
      strIngredient2: 'Triple sec',
      strIngredient3: 'Lime juice',
      strIngredient4: 'Sugar',
      strIngredient5: 'Egg white',
      strIngredient6: 'Mint',
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: '1 1/2 tsp ',
      strMeasure3: '1 tblsp ',
      strMeasure4: '1 tsp ',
      strMeasure5: '1 ',
      strMeasure6: '1 ',
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-09-02 11:26:16',
    },
    {
      idDrink: '17840',
      strDrink: 'Affinity',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: cockTailGlass,
      strInstructions: 'In a mixing glass half-filled with ice cubes, combine all of the ingredients. Stir well. Strain into a cocktail glass.',
      strInstructionsES: 'En un vaso mezclador lleno hasta la mitad con cubitos de hielo, combine todos los ingredientes. Sacudir bien. Colar en un vaso de cóctel.',
      strInstructionsDE: 'In einem Mischglas, das halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut umrühren. In ein Cocktailglas abseihen.',
      strInstructionsFR: null,
      strInstructionsIT: 'In un mixing glass riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti. Filtrare in un bicchiere da cocktail. Mescolare bene.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/wzdtnn1582477684.jpg',
      strIngredient1: 'Scotch',
      strIngredient2: 'Sweet Vermouth',
      strIngredient3: 'Dry Vermouth',
      strIngredient4: 'Orange bitters',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '1 oz ',
      strMeasure4: '2 dashes ',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2017-09-07 21:44:05',
    },
  ],
};
