export const mealIngredientChicken = {
  meals: [
    {
      strMeal: 'Brown Stew Chicken',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sypxpx1515365095.jpg',
      idMeal: '52940',
    },
    {
      strMeal: 'Chicken & mushroom Hotpot',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuuspp1511297945.jpg',
      idMeal: '52846',
    },
    {
      strMeal: 'Chicken Alfredo Primavera',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg',
      idMeal: '52796',
    },
    {
      strMeal: 'Chicken Basquaise',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wruvqv1511880994.jpg',
      idMeal: '52934',
    },
    {
      strMeal: 'Chicken Congee',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1529446352.jpg',
      idMeal: '52956',
    },
    {
      strMeal: 'Chicken Handi',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg',
      idMeal: '52795',
    },
    {
      strMeal: 'Kentucky Fried Chicken',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/xqusqy1487348868.jpg',
      idMeal: '52813',
    },
    {
      strMeal: 'Kung Pao Chicken',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1525872624.jpg',
      idMeal: '52945',
    },
    {
      strMeal: 'Pad See Ew',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg',
      idMeal: '52774',
    },
    {
      strMeal: 'Piri-piri chicken and slaw',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/hglsbl1614346998.jpg',
      idMeal: '53039',
    },
    {
      strMeal: 'Thai Green Curry',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sstssx1487349585.jpg',
      idMeal: '52814',
    },
  ],
};

export const mealNameRisotto = [
  {
    idMeal: '52823',
    strMeal: 'Salmon Prawn Risotto',
    strDrinkAlternate: null,
    strCategory: 'Seafood',
    strArea: 'Italian',
    strInstructions: 'Melt the butter in a thick-based pan and gently cook the onion without colour until it is soft.\r\nAdd the rice and stir to coat all the grains in the butter\r\nAdd the wine and cook gently stirring until it is absorbed\r\nGradually add the hot stock, stirring until each addition is absorbed. Keep stirring until the rice is tender\r\nSeason with the lemon juice and zest, and pepper to taste. (there will probably be sufficient saltiness from the salmon to not need to add salt) Stir gently to heat through\r\nServe scattered with the Parmesan and seasonal vegetables.\r\nGrill the salmon and gently place onto the risotto with the prawns and asparagus',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/xxrxux1503070723.jpg',
    strTags: 'Fish',
    strYoutube: 'https://www.youtube.com/watch?v=V2PMvBv52IE',
    strIngredient1: 'butter',
    strIngredient2: 'onion',
    strIngredient3: 'rice',
    strIngredient4: 'white wine',
    strIngredient5: 'vegetable stock',
    strIngredient6: 'lemon',
    strIngredient7: 'King Prawns',
    strIngredient8: 'salmon',
    strIngredient9: 'asparagus',
    strIngredient10: 'black pepper',
    strIngredient11: 'Parmesan',
    strIngredient12: '',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strIngredient16: '',
    strIngredient17: '',
    strIngredient18: '',
    strIngredient19: '',
    strIngredient20: '',
    strMeasure1: '50g/2oz',
    strMeasure2: '1 finely chopped ',
    strMeasure3: '150g',
    strMeasure4: '125ml ',
    strMeasure5: '1 litre hot',
    strMeasure6: 'The juice and zest of one',
    strMeasure7: '240g large',
    strMeasure8: '150g',
    strMeasure9: '100g tips blanched briefly in boiling water',
    strMeasure10: 'ground',
    strMeasure11: '50g shavings',
    strMeasure12: '',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    strMeasure16: '',
    strMeasure17: '',
    strMeasure18: '',
    strMeasure19: '',
    strMeasure20: '',
    strSource: 'http://www.rangemaster.co.uk/rangemaster-owners/recipes-ideas-inspiration/recipes/mains/prawn-and-hot-smoked-salmon-risotto-with-asparagus',
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
];

const fileName = 'http://localhost:3001/static/js/bundle.js';

export const mealFirstLetterM = [
  {
    name: 'State',
    value: [
      {
        idMeal: '52777',
        strMeal: 'Mediterranean Pasta Salad',
        strDrinkAlternate: null,
        strCategory: 'Seafood',
        strArea: 'Italian',
        strInstructions: 'Bring a large saucepan of salted water to the boil\r\nAdd the pasta, stir once and cook for about 10 minutes or as directed on the packet.\r\nMeanwhile, wash the tomatoes and cut into quarters. Slice the olives. Wash the basil.\r\nPut the tomatoes into a salad bowl and tear the basil leaves over them. Add a tablespoon of olive oil and mix.\r\nWhen the pasta is ready, drain into a colander and run cold water over it to cool it quickly.\r\nToss the pasta into the salad bowl with the tomatoes and basil.\r\nAdd...',
        strMealThumb: 'https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg',
        strTags: 'Pasta,Baking',
        strYoutube: 'https://www.youtube.com/watch?v=e52IL8zYmaE',
        strIngredient1: 'mozzarella balls',
        strIngredient2: 'baby plum tomatoes',
        strIngredient3: 'fresh basil',
        strIngredient4: 'farfalle',
        strIngredient5: 'extra virgin olive oil',
        strIngredient6: 'Green Olives',
        strIngredient7: 'tuna',
        strIngredient8: 'salt',
        strIngredient9: 'pepper',
        strIngredient10: '',
        strIngredient11: '',
        strIngredient12: '',
        strIngredient13: '',
        strIngredient14: '',
        strIngredient15: '',
        strIngredient16: null,
        strIngredient17: null,
        strIngredient18: null,
        strIngredient19: null,
        strIngredient20: null,
        strMeasure1: '200 g',
        strMeasure2: '250 g',
        strMeasure3: '1  bunch',
        strMeasure4: '350 g',
        strMeasure5: '3  tablespoons',
        strMeasure6: '40 g',
        strMeasure7: '200 g',
        strMeasure8: 'to taste',
        strMeasure9: 'to taste',
        strMeasure10: '',
        strMeasure11: '',
        strMeasure12: '',
        strMeasure13: '',
        strMeasure14: '',
        strMeasure15: '',
        strMeasure16: null,
        strMeasure17: null,
        strMeasure18: null,
        strMeasure19: null,
        strMeasure20: null,
        strSource: 'https://thelemonsqueezy.com/recipe/mediterranean-pasta-salad/',
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null,
      },
      '{dateModified: null, idMeal: "52827", strArea: "Tha…}',
      '{dateModified: null, idMeal: "52864", strArea: "Bri…}',
      '{dateModified: null, idMeal: "52865", strArea: "Ind…}',
      '{dateModified: null, idMeal: "52876", strArea: "Bri…}',
      '{dateModified: null, idMeal: "52880", strArea: "Bri…}',
      '{dateModified: null, idMeal: "52900", strArea: "Bri…}',
      '{dateModified: null, idMeal: "52927", strArea: "Can…}',
      '{dateModified: null, idMeal: "52947", strArea: "Chi…}',
      '{dateModified: null, idMeal: "52968", strArea: "Ken…}',
      '{dateModified: null, idMeal: "52991", strArea: "Bri…}',
      '{dateModified: null, idMeal: "53006", strArea: "Gre…}',
      '{dateModified: null, idMeal: "53029", strArea: "Egy…}',
      '{dateModified: null, idMeal: "53038", strArea: "Iri…}',
      '{dateModified: null, idMeal: "53047", strArea: "Mor…}',
      '{dateModified: null, idMeal: "53048", strArea: "Mal…}',
      '{dateModified: null, idMeal: "53059", strArea: "Cro…}',
    ],
    subHooks: [],
    hookSource: {
      lineNumber: 771,
      functionName: 'AppProvider',
      fileName,
      columnNumber: 74,
    },
  },
  {
    name: 'State',
    value: {
      pathname: '/meals',
      searchOption: 'First letter',
      searchInput: 'm',
    },
    subHooks: [],
    hookSource: {
      lineNumber: 772,
      functionName: 'AppProvider',
      fileName,
      columnNumber: 88,
    },
  },
  {
    name: 'Callback',
    value: 'ƒ () {}',
    subHooks: [],
    hookSource: {
      lineNumber: 788,
      functionName: 'AppProvider',
      fileName,
      columnNumber: 78,
    },
  },
  {
    name: 'Callback',
    value: 'ƒ () {}',
    subHooks: [],
    hookSource: {
      lineNumber: 825,
      functionName: 'AppProvider',
      fileName,
      columnNumber: 79,
    },
  },
  {
    name: 'Effect',
    value: 'ƒ () {}',
    subHooks: [],
    hookSource: {
      lineNumber: 862,
      functionName: 'AppProvider',
      fileName,
      columnNumber: 51,
    },
  },
  {
    name: 'Memo',
    value: {
      data: '[{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, …]',
      getSearchSetup: 'ƒ getSearchSetup() {}',
    },
    subHooks: [],
    hookSource: {
      lineNumber: 871,
      functionName: 'AppProvider',
      fileName,
      columnNumber: 65,
    },
  },
];
